# Generated by Django 4.2.7 on 2024-01-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='customer',
        ),
    ]
