# Generated by Django 4.2.7 on 2024-01-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_flightdeatils'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flightdeatils',
        ),
    ]
