# Generated by Django 4.2.7 on 2024-01-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_flightdeatils'),
    ]

    operations = [
        migrations.CreateModel(
            name='flightdeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2080)),
                ('time', models.CharField(max_length=2080)),
                ('fromp', models.CharField(max_length=2080)),
                ('top', models.CharField(max_length=2080)),
                ('date', models.DateField()),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
